# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lamy_a/rendu/babel/server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lamy_a/rendu/babel/server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lamy_a/rendu/babel/server/CMakeFiles /home/lamy_a/rendu/babel/server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lamy_a/rendu/babel/server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named babel-server

# Build rule for target.
babel-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 babel-server
.PHONY : babel-server

# fast build rule for target.
babel-server/fast:
	$(MAKE) -f CMakeFiles/babel-server.dir/build.make CMakeFiles/babel-server.dir/build
.PHONY : babel-server/fast

#=============================================================================
# Target rules for targets named babel-server-core

# Build rule for target.
babel-server-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 babel-server-core
.PHONY : babel-server-core

# fast build rule for target.
babel-server-core/fast:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/build
.PHONY : babel-server-core/fast

#=============================================================================
# Target rules for targets named channel-service

# Build rule for target.
channel-service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 channel-service
.PHONY : channel-service

# fast build rule for target.
channel-service/fast:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/build
.PHONY : channel-service/fast

#=============================================================================
# Target rules for targets named database-service

# Build rule for target.
database-service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 database-service
.PHONY : database-service

# fast build rule for target.
database-service/fast:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/build
.PHONY : database-service/fast

#=============================================================================
# Target rules for targets named loggin-service

# Build rule for target.
loggin-service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 loggin-service
.PHONY : loggin-service

# fast build rule for target.
loggin-service/fast:
	$(MAKE) -f CMakeFiles/loggin-service.dir/build.make CMakeFiles/loggin-service.dir/build
.PHONY : loggin-service/fast

#=============================================================================
# Target rules for targets named user-service

# Build rule for target.
user-service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 user-service
.PHONY : user-service

# fast build rule for target.
user-service/fast:
	$(MAKE) -f CMakeFiles/user-service.dir/build.make CMakeFiles/user-service.dir/build
.PHONY : user-service/fast

src/UserController.o: src/UserController.cpp.o
.PHONY : src/UserController.o

# target to build an object file
src/UserController.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/UserController.cpp.o
.PHONY : src/UserController.cpp.o

src/UserController.i: src/UserController.cpp.i
.PHONY : src/UserController.i

# target to preprocess a source file
src/UserController.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/UserController.cpp.i
.PHONY : src/UserController.cpp.i

src/UserController.s: src/UserController.cpp.s
.PHONY : src/UserController.s

# target to generate assembly for a file
src/UserController.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/UserController.cpp.s
.PHONY : src/UserController.cpp.s

src/loaders/ClassException.o: src/loaders/ClassException.cpp.o
.PHONY : src/loaders/ClassException.o

# target to build an object file
src/loaders/ClassException.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/loaders/ClassException.cpp.o
.PHONY : src/loaders/ClassException.cpp.o

src/loaders/ClassException.i: src/loaders/ClassException.cpp.i
.PHONY : src/loaders/ClassException.i

# target to preprocess a source file
src/loaders/ClassException.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/loaders/ClassException.cpp.i
.PHONY : src/loaders/ClassException.cpp.i

src/loaders/ClassException.s: src/loaders/ClassException.cpp.s
.PHONY : src/loaders/ClassException.s

# target to generate assembly for a file
src/loaders/ClassException.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/loaders/ClassException.cpp.s
.PHONY : src/loaders/ClassException.cpp.s

src/loaders/UnixLibLoader.o: src/loaders/UnixLibLoader.cpp.o
.PHONY : src/loaders/UnixLibLoader.o

# target to build an object file
src/loaders/UnixLibLoader.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/loaders/UnixLibLoader.cpp.o
.PHONY : src/loaders/UnixLibLoader.cpp.o

src/loaders/UnixLibLoader.i: src/loaders/UnixLibLoader.cpp.i
.PHONY : src/loaders/UnixLibLoader.i

# target to preprocess a source file
src/loaders/UnixLibLoader.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/loaders/UnixLibLoader.cpp.i
.PHONY : src/loaders/UnixLibLoader.cpp.i

src/loaders/UnixLibLoader.s: src/loaders/UnixLibLoader.cpp.s
.PHONY : src/loaders/UnixLibLoader.s

# target to generate assembly for a file
src/loaders/UnixLibLoader.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/loaders/UnixLibLoader.cpp.s
.PHONY : src/loaders/UnixLibLoader.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server.dir/build.make CMakeFiles/babel-server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server.dir/build.make CMakeFiles/babel-server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server.dir/build.make CMakeFiles/babel-server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/managers/BoostManager.o: src/managers/BoostManager.cpp.o
.PHONY : src/managers/BoostManager.o

# target to build an object file
src/managers/BoostManager.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/managers/BoostManager.cpp.o
.PHONY : src/managers/BoostManager.cpp.o

src/managers/BoostManager.i: src/managers/BoostManager.cpp.i
.PHONY : src/managers/BoostManager.i

# target to preprocess a source file
src/managers/BoostManager.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/managers/BoostManager.cpp.i
.PHONY : src/managers/BoostManager.cpp.i

src/managers/BoostManager.s: src/managers/BoostManager.cpp.s
.PHONY : src/managers/BoostManager.s

# target to generate assembly for a file
src/managers/BoostManager.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/managers/BoostManager.cpp.s
.PHONY : src/managers/BoostManager.cpp.s

src/network/AServerSocket.o: src/network/AServerSocket.cpp.o
.PHONY : src/network/AServerSocket.o

# target to build an object file
src/network/AServerSocket.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/AServerSocket.cpp.o
.PHONY : src/network/AServerSocket.cpp.o

src/network/AServerSocket.i: src/network/AServerSocket.cpp.i
.PHONY : src/network/AServerSocket.i

# target to preprocess a source file
src/network/AServerSocket.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/AServerSocket.cpp.i
.PHONY : src/network/AServerSocket.cpp.i

src/network/AServerSocket.s: src/network/AServerSocket.cpp.s
.PHONY : src/network/AServerSocket.s

# target to generate assembly for a file
src/network/AServerSocket.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/AServerSocket.cpp.s
.PHONY : src/network/AServerSocket.cpp.s

src/network/ASocket.o: src/network/ASocket.cpp.o
.PHONY : src/network/ASocket.o

# target to build an object file
src/network/ASocket.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/ASocket.cpp.o
.PHONY : src/network/ASocket.cpp.o

src/network/ASocket.i: src/network/ASocket.cpp.i
.PHONY : src/network/ASocket.i

# target to preprocess a source file
src/network/ASocket.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/ASocket.cpp.i
.PHONY : src/network/ASocket.cpp.i

src/network/ASocket.s: src/network/ASocket.cpp.s
.PHONY : src/network/ASocket.s

# target to generate assembly for a file
src/network/ASocket.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/ASocket.cpp.s
.PHONY : src/network/ASocket.cpp.s

src/network/BoostClientSocket.o: src/network/BoostClientSocket.cpp.o
.PHONY : src/network/BoostClientSocket.o

# target to build an object file
src/network/BoostClientSocket.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/BoostClientSocket.cpp.o
.PHONY : src/network/BoostClientSocket.cpp.o

src/network/BoostClientSocket.i: src/network/BoostClientSocket.cpp.i
.PHONY : src/network/BoostClientSocket.i

# target to preprocess a source file
src/network/BoostClientSocket.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/BoostClientSocket.cpp.i
.PHONY : src/network/BoostClientSocket.cpp.i

src/network/BoostClientSocket.s: src/network/BoostClientSocket.cpp.s
.PHONY : src/network/BoostClientSocket.s

# target to generate assembly for a file
src/network/BoostClientSocket.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/BoostClientSocket.cpp.s
.PHONY : src/network/BoostClientSocket.cpp.s

src/network/BoostServer.o: src/network/BoostServer.cpp.o
.PHONY : src/network/BoostServer.o

# target to build an object file
src/network/BoostServer.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/BoostServer.cpp.o
.PHONY : src/network/BoostServer.cpp.o

src/network/BoostServer.i: src/network/BoostServer.cpp.i
.PHONY : src/network/BoostServer.i

# target to preprocess a source file
src/network/BoostServer.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/BoostServer.cpp.i
.PHONY : src/network/BoostServer.cpp.i

src/network/BoostServer.s: src/network/BoostServer.cpp.s
.PHONY : src/network/BoostServer.s

# target to generate assembly for a file
src/network/BoostServer.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/BoostServer.cpp.s
.PHONY : src/network/BoostServer.cpp.s

src/network/BoostServerAcceptor.o: src/network/BoostServerAcceptor.cpp.o
.PHONY : src/network/BoostServerAcceptor.o

# target to build an object file
src/network/BoostServerAcceptor.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/BoostServerAcceptor.cpp.o
.PHONY : src/network/BoostServerAcceptor.cpp.o

src/network/BoostServerAcceptor.i: src/network/BoostServerAcceptor.cpp.i
.PHONY : src/network/BoostServerAcceptor.i

# target to preprocess a source file
src/network/BoostServerAcceptor.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/BoostServerAcceptor.cpp.i
.PHONY : src/network/BoostServerAcceptor.cpp.i

src/network/BoostServerAcceptor.s: src/network/BoostServerAcceptor.cpp.s
.PHONY : src/network/BoostServerAcceptor.s

# target to generate assembly for a file
src/network/BoostServerAcceptor.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/network/BoostServerAcceptor.cpp.s
.PHONY : src/network/BoostServerAcceptor.cpp.s

src/packets/APacket.o: src/packets/APacket.cpp.o
.PHONY : src/packets/APacket.o

# target to build an object file
src/packets/APacket.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/APacket.cpp.o
.PHONY : src/packets/APacket.cpp.o

src/packets/APacket.i: src/packets/APacket.cpp.i
.PHONY : src/packets/APacket.i

# target to preprocess a source file
src/packets/APacket.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/APacket.cpp.i
.PHONY : src/packets/APacket.cpp.i

src/packets/APacket.s: src/packets/APacket.cpp.s
.PHONY : src/packets/APacket.s

# target to generate assembly for a file
src/packets/APacket.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/APacket.cpp.s
.PHONY : src/packets/APacket.cpp.s

src/packets/PacketAddContact.o: src/packets/PacketAddContact.cpp.o
.PHONY : src/packets/PacketAddContact.o

# target to build an object file
src/packets/PacketAddContact.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketAddContact.cpp.o
.PHONY : src/packets/PacketAddContact.cpp.o

src/packets/PacketAddContact.i: src/packets/PacketAddContact.cpp.i
.PHONY : src/packets/PacketAddContact.i

# target to preprocess a source file
src/packets/PacketAddContact.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketAddContact.cpp.i
.PHONY : src/packets/PacketAddContact.cpp.i

src/packets/PacketAddContact.s: src/packets/PacketAddContact.cpp.s
.PHONY : src/packets/PacketAddContact.s

# target to generate assembly for a file
src/packets/PacketAddContact.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketAddContact.cpp.s
.PHONY : src/packets/PacketAddContact.cpp.s

src/packets/PacketAnswer.o: src/packets/PacketAnswer.cpp.o
.PHONY : src/packets/PacketAnswer.o

# target to build an object file
src/packets/PacketAnswer.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketAnswer.cpp.o
.PHONY : src/packets/PacketAnswer.cpp.o

src/packets/PacketAnswer.i: src/packets/PacketAnswer.cpp.i
.PHONY : src/packets/PacketAnswer.i

# target to preprocess a source file
src/packets/PacketAnswer.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketAnswer.cpp.i
.PHONY : src/packets/PacketAnswer.cpp.i

src/packets/PacketAnswer.s: src/packets/PacketAnswer.cpp.s
.PHONY : src/packets/PacketAnswer.s

# target to generate assembly for a file
src/packets/PacketAnswer.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketAnswer.cpp.s
.PHONY : src/packets/PacketAnswer.cpp.s

src/packets/PacketAuthentification.o: src/packets/PacketAuthentification.cpp.o
.PHONY : src/packets/PacketAuthentification.o

# target to build an object file
src/packets/PacketAuthentification.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketAuthentification.cpp.o
.PHONY : src/packets/PacketAuthentification.cpp.o

src/packets/PacketAuthentification.i: src/packets/PacketAuthentification.cpp.i
.PHONY : src/packets/PacketAuthentification.i

# target to preprocess a source file
src/packets/PacketAuthentification.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketAuthentification.cpp.i
.PHONY : src/packets/PacketAuthentification.cpp.i

src/packets/PacketAuthentification.s: src/packets/PacketAuthentification.cpp.s
.PHONY : src/packets/PacketAuthentification.s

# target to generate assembly for a file
src/packets/PacketAuthentification.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketAuthentification.cpp.s
.PHONY : src/packets/PacketAuthentification.cpp.s

src/packets/PacketCreateChannel.o: src/packets/PacketCreateChannel.cpp.o
.PHONY : src/packets/PacketCreateChannel.o

# target to build an object file
src/packets/PacketCreateChannel.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketCreateChannel.cpp.o
.PHONY : src/packets/PacketCreateChannel.cpp.o

src/packets/PacketCreateChannel.i: src/packets/PacketCreateChannel.cpp.i
.PHONY : src/packets/PacketCreateChannel.i

# target to preprocess a source file
src/packets/PacketCreateChannel.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketCreateChannel.cpp.i
.PHONY : src/packets/PacketCreateChannel.cpp.i

src/packets/PacketCreateChannel.s: src/packets/PacketCreateChannel.cpp.s
.PHONY : src/packets/PacketCreateChannel.s

# target to generate assembly for a file
src/packets/PacketCreateChannel.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketCreateChannel.cpp.s
.PHONY : src/packets/PacketCreateChannel.cpp.s

src/packets/PacketFactory.o: src/packets/PacketFactory.cpp.o
.PHONY : src/packets/PacketFactory.o

# target to build an object file
src/packets/PacketFactory.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketFactory.cpp.o
.PHONY : src/packets/PacketFactory.cpp.o

src/packets/PacketFactory.i: src/packets/PacketFactory.cpp.i
.PHONY : src/packets/PacketFactory.i

# target to preprocess a source file
src/packets/PacketFactory.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketFactory.cpp.i
.PHONY : src/packets/PacketFactory.cpp.i

src/packets/PacketFactory.s: src/packets/PacketFactory.cpp.s
.PHONY : src/packets/PacketFactory.s

# target to generate assembly for a file
src/packets/PacketFactory.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketFactory.cpp.s
.PHONY : src/packets/PacketFactory.cpp.s

src/packets/PacketGetUserInfos.o: src/packets/PacketGetUserInfos.cpp.o
.PHONY : src/packets/PacketGetUserInfos.o

# target to build an object file
src/packets/PacketGetUserInfos.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketGetUserInfos.cpp.o
.PHONY : src/packets/PacketGetUserInfos.cpp.o

src/packets/PacketGetUserInfos.i: src/packets/PacketGetUserInfos.cpp.i
.PHONY : src/packets/PacketGetUserInfos.i

# target to preprocess a source file
src/packets/PacketGetUserInfos.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketGetUserInfos.cpp.i
.PHONY : src/packets/PacketGetUserInfos.cpp.i

src/packets/PacketGetUserInfos.s: src/packets/PacketGetUserInfos.cpp.s
.PHONY : src/packets/PacketGetUserInfos.s

# target to generate assembly for a file
src/packets/PacketGetUserInfos.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketGetUserInfos.cpp.s
.PHONY : src/packets/PacketGetUserInfos.cpp.s

src/packets/PacketHello.o: src/packets/PacketHello.cpp.o
.PHONY : src/packets/PacketHello.o

# target to build an object file
src/packets/PacketHello.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketHello.cpp.o
.PHONY : src/packets/PacketHello.cpp.o

src/packets/PacketHello.i: src/packets/PacketHello.cpp.i
.PHONY : src/packets/PacketHello.i

# target to preprocess a source file
src/packets/PacketHello.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketHello.cpp.i
.PHONY : src/packets/PacketHello.cpp.i

src/packets/PacketHello.s: src/packets/PacketHello.cpp.s
.PHONY : src/packets/PacketHello.s

# target to generate assembly for a file
src/packets/PacketHello.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketHello.cpp.s
.PHONY : src/packets/PacketHello.cpp.s

src/packets/PacketLoginSuccess.o: src/packets/PacketLoginSuccess.cpp.o
.PHONY : src/packets/PacketLoginSuccess.o

# target to build an object file
src/packets/PacketLoginSuccess.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketLoginSuccess.cpp.o
.PHONY : src/packets/PacketLoginSuccess.cpp.o

src/packets/PacketLoginSuccess.i: src/packets/PacketLoginSuccess.cpp.i
.PHONY : src/packets/PacketLoginSuccess.i

# target to preprocess a source file
src/packets/PacketLoginSuccess.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketLoginSuccess.cpp.i
.PHONY : src/packets/PacketLoginSuccess.cpp.i

src/packets/PacketLoginSuccess.s: src/packets/PacketLoginSuccess.cpp.s
.PHONY : src/packets/PacketLoginSuccess.s

# target to generate assembly for a file
src/packets/PacketLoginSuccess.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketLoginSuccess.cpp.s
.PHONY : src/packets/PacketLoginSuccess.cpp.s

src/packets/PacketRegister.o: src/packets/PacketRegister.cpp.o
.PHONY : src/packets/PacketRegister.o

# target to build an object file
src/packets/PacketRegister.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketRegister.cpp.o
.PHONY : src/packets/PacketRegister.cpp.o

src/packets/PacketRegister.i: src/packets/PacketRegister.cpp.i
.PHONY : src/packets/PacketRegister.i

# target to preprocess a source file
src/packets/PacketRegister.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketRegister.cpp.i
.PHONY : src/packets/PacketRegister.cpp.i

src/packets/PacketRegister.s: src/packets/PacketRegister.cpp.s
.PHONY : src/packets/PacketRegister.s

# target to generate assembly for a file
src/packets/PacketRegister.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketRegister.cpp.s
.PHONY : src/packets/PacketRegister.cpp.s

src/packets/PacketUpdateStatus.o: src/packets/PacketUpdateStatus.cpp.o
.PHONY : src/packets/PacketUpdateStatus.o

# target to build an object file
src/packets/PacketUpdateStatus.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketUpdateStatus.cpp.o
.PHONY : src/packets/PacketUpdateStatus.cpp.o

src/packets/PacketUpdateStatus.i: src/packets/PacketUpdateStatus.cpp.i
.PHONY : src/packets/PacketUpdateStatus.i

# target to preprocess a source file
src/packets/PacketUpdateStatus.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketUpdateStatus.cpp.i
.PHONY : src/packets/PacketUpdateStatus.cpp.i

src/packets/PacketUpdateStatus.s: src/packets/PacketUpdateStatus.cpp.s
.PHONY : src/packets/PacketUpdateStatus.s

# target to generate assembly for a file
src/packets/PacketUpdateStatus.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketUpdateStatus.cpp.s
.PHONY : src/packets/PacketUpdateStatus.cpp.s

src/packets/PacketUpdateUsername.o: src/packets/PacketUpdateUsername.cpp.o
.PHONY : src/packets/PacketUpdateUsername.o

# target to build an object file
src/packets/PacketUpdateUsername.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketUpdateUsername.cpp.o
.PHONY : src/packets/PacketUpdateUsername.cpp.o

src/packets/PacketUpdateUsername.i: src/packets/PacketUpdateUsername.cpp.i
.PHONY : src/packets/PacketUpdateUsername.i

# target to preprocess a source file
src/packets/PacketUpdateUsername.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketUpdateUsername.cpp.i
.PHONY : src/packets/PacketUpdateUsername.cpp.i

src/packets/PacketUpdateUsername.s: src/packets/PacketUpdateUsername.cpp.s
.PHONY : src/packets/PacketUpdateUsername.s

# target to generate assembly for a file
src/packets/PacketUpdateUsername.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketUpdateUsername.cpp.s
.PHONY : src/packets/PacketUpdateUsername.cpp.s

src/packets/PacketUserInfos.o: src/packets/PacketUserInfos.cpp.o
.PHONY : src/packets/PacketUserInfos.o

# target to build an object file
src/packets/PacketUserInfos.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketUserInfos.cpp.o
.PHONY : src/packets/PacketUserInfos.cpp.o

src/packets/PacketUserInfos.i: src/packets/PacketUserInfos.cpp.i
.PHONY : src/packets/PacketUserInfos.i

# target to preprocess a source file
src/packets/PacketUserInfos.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketUserInfos.cpp.i
.PHONY : src/packets/PacketUserInfos.cpp.i

src/packets/PacketUserInfos.s: src/packets/PacketUserInfos.cpp.s
.PHONY : src/packets/PacketUserInfos.s

# target to generate assembly for a file
src/packets/PacketUserInfos.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/packets/PacketUserInfos.cpp.s
.PHONY : src/packets/PacketUserInfos.cpp.s

src/services/ServiceManager.o: src/services/ServiceManager.cpp.o
.PHONY : src/services/ServiceManager.o

# target to build an object file
src/services/ServiceManager.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/services/ServiceManager.cpp.o
.PHONY : src/services/ServiceManager.cpp.o

src/services/ServiceManager.i: src/services/ServiceManager.cpp.i
.PHONY : src/services/ServiceManager.i

# target to preprocess a source file
src/services/ServiceManager.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/services/ServiceManager.cpp.i
.PHONY : src/services/ServiceManager.cpp.i

src/services/ServiceManager.s: src/services/ServiceManager.cpp.s
.PHONY : src/services/ServiceManager.s

# target to generate assembly for a file
src/services/ServiceManager.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/services/ServiceManager.cpp.s
.PHONY : src/services/ServiceManager.cpp.s

src/services/UserData.o: src/services/UserData.cpp.o
.PHONY : src/services/UserData.o

# target to build an object file
src/services/UserData.cpp.o:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/UserData.cpp.o
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/UserData.cpp.o
	$(MAKE) -f CMakeFiles/loggin-service.dir/build.make CMakeFiles/loggin-service.dir/src/services/UserData.cpp.o
	$(MAKE) -f CMakeFiles/user-service.dir/build.make CMakeFiles/user-service.dir/src/services/UserData.cpp.o
.PHONY : src/services/UserData.cpp.o

src/services/UserData.i: src/services/UserData.cpp.i
.PHONY : src/services/UserData.i

# target to preprocess a source file
src/services/UserData.cpp.i:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/UserData.cpp.i
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/UserData.cpp.i
	$(MAKE) -f CMakeFiles/loggin-service.dir/build.make CMakeFiles/loggin-service.dir/src/services/UserData.cpp.i
	$(MAKE) -f CMakeFiles/user-service.dir/build.make CMakeFiles/user-service.dir/src/services/UserData.cpp.i
.PHONY : src/services/UserData.cpp.i

src/services/UserData.s: src/services/UserData.cpp.s
.PHONY : src/services/UserData.s

# target to generate assembly for a file
src/services/UserData.cpp.s:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/UserData.cpp.s
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/UserData.cpp.s
	$(MAKE) -f CMakeFiles/loggin-service.dir/build.make CMakeFiles/loggin-service.dir/src/services/UserData.cpp.s
	$(MAKE) -f CMakeFiles/user-service.dir/build.make CMakeFiles/user-service.dir/src/services/UserData.cpp.s
.PHONY : src/services/UserData.cpp.s

src/services/channel-service/ChannelService.o: src/services/channel-service/ChannelService.cpp.o
.PHONY : src/services/channel-service/ChannelService.o

# target to build an object file
src/services/channel-service/ChannelService.cpp.o:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/channel-service/ChannelService.cpp.o
.PHONY : src/services/channel-service/ChannelService.cpp.o

src/services/channel-service/ChannelService.i: src/services/channel-service/ChannelService.cpp.i
.PHONY : src/services/channel-service/ChannelService.i

# target to preprocess a source file
src/services/channel-service/ChannelService.cpp.i:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/channel-service/ChannelService.cpp.i
.PHONY : src/services/channel-service/ChannelService.cpp.i

src/services/channel-service/ChannelService.s: src/services/channel-service/ChannelService.cpp.s
.PHONY : src/services/channel-service/ChannelService.s

# target to generate assembly for a file
src/services/channel-service/ChannelService.cpp.s:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/channel-service/ChannelService.cpp.s
.PHONY : src/services/channel-service/ChannelService.cpp.s

src/services/channel-service/Room.o: src/services/channel-service/Room.cpp.o
.PHONY : src/services/channel-service/Room.o

# target to build an object file
src/services/channel-service/Room.cpp.o:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/channel-service/Room.cpp.o
.PHONY : src/services/channel-service/Room.cpp.o

src/services/channel-service/Room.i: src/services/channel-service/Room.cpp.i
.PHONY : src/services/channel-service/Room.i

# target to preprocess a source file
src/services/channel-service/Room.cpp.i:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/channel-service/Room.cpp.i
.PHONY : src/services/channel-service/Room.cpp.i

src/services/channel-service/Room.s: src/services/channel-service/Room.cpp.s
.PHONY : src/services/channel-service/Room.s

# target to generate assembly for a file
src/services/channel-service/Room.cpp.s:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/channel-service/Room.cpp.s
.PHONY : src/services/channel-service/Room.cpp.s

src/services/channel-service/creatorChannelService.o: src/services/channel-service/creatorChannelService.cpp.o
.PHONY : src/services/channel-service/creatorChannelService.o

# target to build an object file
src/services/channel-service/creatorChannelService.cpp.o:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/channel-service/creatorChannelService.cpp.o
.PHONY : src/services/channel-service/creatorChannelService.cpp.o

src/services/channel-service/creatorChannelService.i: src/services/channel-service/creatorChannelService.cpp.i
.PHONY : src/services/channel-service/creatorChannelService.i

# target to preprocess a source file
src/services/channel-service/creatorChannelService.cpp.i:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/channel-service/creatorChannelService.cpp.i
.PHONY : src/services/channel-service/creatorChannelService.cpp.i

src/services/channel-service/creatorChannelService.s: src/services/channel-service/creatorChannelService.cpp.s
.PHONY : src/services/channel-service/creatorChannelService.s

# target to generate assembly for a file
src/services/channel-service/creatorChannelService.cpp.s:
	$(MAKE) -f CMakeFiles/channel-service.dir/build.make CMakeFiles/channel-service.dir/src/services/channel-service/creatorChannelService.cpp.s
.PHONY : src/services/channel-service/creatorChannelService.cpp.s

src/services/database-service/DatabaseException.o: src/services/database-service/DatabaseException.cpp.o
.PHONY : src/services/database-service/DatabaseException.o

# target to build an object file
src/services/database-service/DatabaseException.cpp.o:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/DatabaseException.cpp.o
.PHONY : src/services/database-service/DatabaseException.cpp.o

src/services/database-service/DatabaseException.i: src/services/database-service/DatabaseException.cpp.i
.PHONY : src/services/database-service/DatabaseException.i

# target to preprocess a source file
src/services/database-service/DatabaseException.cpp.i:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/DatabaseException.cpp.i
.PHONY : src/services/database-service/DatabaseException.cpp.i

src/services/database-service/DatabaseException.s: src/services/database-service/DatabaseException.cpp.s
.PHONY : src/services/database-service/DatabaseException.s

# target to generate assembly for a file
src/services/database-service/DatabaseException.cpp.s:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/DatabaseException.cpp.s
.PHONY : src/services/database-service/DatabaseException.cpp.s

src/services/database-service/FileDatabase.o: src/services/database-service/FileDatabase.cpp.o
.PHONY : src/services/database-service/FileDatabase.o

# target to build an object file
src/services/database-service/FileDatabase.cpp.o:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/FileDatabase.cpp.o
.PHONY : src/services/database-service/FileDatabase.cpp.o

src/services/database-service/FileDatabase.i: src/services/database-service/FileDatabase.cpp.i
.PHONY : src/services/database-service/FileDatabase.i

# target to preprocess a source file
src/services/database-service/FileDatabase.cpp.i:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/FileDatabase.cpp.i
.PHONY : src/services/database-service/FileDatabase.cpp.i

src/services/database-service/FileDatabase.s: src/services/database-service/FileDatabase.cpp.s
.PHONY : src/services/database-service/FileDatabase.s

# target to generate assembly for a file
src/services/database-service/FileDatabase.cpp.s:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/FileDatabase.cpp.s
.PHONY : src/services/database-service/FileDatabase.cpp.s

src/services/database-service/FileHelper.o: src/services/database-service/FileHelper.cpp.o
.PHONY : src/services/database-service/FileHelper.o

# target to build an object file
src/services/database-service/FileHelper.cpp.o:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/FileHelper.cpp.o
.PHONY : src/services/database-service/FileHelper.cpp.o

src/services/database-service/FileHelper.i: src/services/database-service/FileHelper.cpp.i
.PHONY : src/services/database-service/FileHelper.i

# target to preprocess a source file
src/services/database-service/FileHelper.cpp.i:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/FileHelper.cpp.i
.PHONY : src/services/database-service/FileHelper.cpp.i

src/services/database-service/FileHelper.s: src/services/database-service/FileHelper.cpp.s
.PHONY : src/services/database-service/FileHelper.s

# target to generate assembly for a file
src/services/database-service/FileHelper.cpp.s:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/FileHelper.cpp.s
.PHONY : src/services/database-service/FileHelper.cpp.s

src/services/database-service/creatorDatabaseService.o: src/services/database-service/creatorDatabaseService.cpp.o
.PHONY : src/services/database-service/creatorDatabaseService.o

# target to build an object file
src/services/database-service/creatorDatabaseService.cpp.o:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/creatorDatabaseService.cpp.o
.PHONY : src/services/database-service/creatorDatabaseService.cpp.o

src/services/database-service/creatorDatabaseService.i: src/services/database-service/creatorDatabaseService.cpp.i
.PHONY : src/services/database-service/creatorDatabaseService.i

# target to preprocess a source file
src/services/database-service/creatorDatabaseService.cpp.i:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/creatorDatabaseService.cpp.i
.PHONY : src/services/database-service/creatorDatabaseService.cpp.i

src/services/database-service/creatorDatabaseService.s: src/services/database-service/creatorDatabaseService.cpp.s
.PHONY : src/services/database-service/creatorDatabaseService.s

# target to generate assembly for a file
src/services/database-service/creatorDatabaseService.cpp.s:
	$(MAKE) -f CMakeFiles/database-service.dir/build.make CMakeFiles/database-service.dir/src/services/database-service/creatorDatabaseService.cpp.s
.PHONY : src/services/database-service/creatorDatabaseService.cpp.s

src/services/loggin-service/LogginService.o: src/services/loggin-service/LogginService.cpp.o
.PHONY : src/services/loggin-service/LogginService.o

# target to build an object file
src/services/loggin-service/LogginService.cpp.o:
	$(MAKE) -f CMakeFiles/loggin-service.dir/build.make CMakeFiles/loggin-service.dir/src/services/loggin-service/LogginService.cpp.o
.PHONY : src/services/loggin-service/LogginService.cpp.o

src/services/loggin-service/LogginService.i: src/services/loggin-service/LogginService.cpp.i
.PHONY : src/services/loggin-service/LogginService.i

# target to preprocess a source file
src/services/loggin-service/LogginService.cpp.i:
	$(MAKE) -f CMakeFiles/loggin-service.dir/build.make CMakeFiles/loggin-service.dir/src/services/loggin-service/LogginService.cpp.i
.PHONY : src/services/loggin-service/LogginService.cpp.i

src/services/loggin-service/LogginService.s: src/services/loggin-service/LogginService.cpp.s
.PHONY : src/services/loggin-service/LogginService.s

# target to generate assembly for a file
src/services/loggin-service/LogginService.cpp.s:
	$(MAKE) -f CMakeFiles/loggin-service.dir/build.make CMakeFiles/loggin-service.dir/src/services/loggin-service/LogginService.cpp.s
.PHONY : src/services/loggin-service/LogginService.cpp.s

src/services/loggin-service/creatorLogginService.o: src/services/loggin-service/creatorLogginService.cpp.o
.PHONY : src/services/loggin-service/creatorLogginService.o

# target to build an object file
src/services/loggin-service/creatorLogginService.cpp.o:
	$(MAKE) -f CMakeFiles/loggin-service.dir/build.make CMakeFiles/loggin-service.dir/src/services/loggin-service/creatorLogginService.cpp.o
.PHONY : src/services/loggin-service/creatorLogginService.cpp.o

src/services/loggin-service/creatorLogginService.i: src/services/loggin-service/creatorLogginService.cpp.i
.PHONY : src/services/loggin-service/creatorLogginService.i

# target to preprocess a source file
src/services/loggin-service/creatorLogginService.cpp.i:
	$(MAKE) -f CMakeFiles/loggin-service.dir/build.make CMakeFiles/loggin-service.dir/src/services/loggin-service/creatorLogginService.cpp.i
.PHONY : src/services/loggin-service/creatorLogginService.cpp.i

src/services/loggin-service/creatorLogginService.s: src/services/loggin-service/creatorLogginService.cpp.s
.PHONY : src/services/loggin-service/creatorLogginService.s

# target to generate assembly for a file
src/services/loggin-service/creatorLogginService.cpp.s:
	$(MAKE) -f CMakeFiles/loggin-service.dir/build.make CMakeFiles/loggin-service.dir/src/services/loggin-service/creatorLogginService.cpp.s
.PHONY : src/services/loggin-service/creatorLogginService.cpp.s

src/services/user-service/UserService.o: src/services/user-service/UserService.cpp.o
.PHONY : src/services/user-service/UserService.o

# target to build an object file
src/services/user-service/UserService.cpp.o:
	$(MAKE) -f CMakeFiles/user-service.dir/build.make CMakeFiles/user-service.dir/src/services/user-service/UserService.cpp.o
.PHONY : src/services/user-service/UserService.cpp.o

src/services/user-service/UserService.i: src/services/user-service/UserService.cpp.i
.PHONY : src/services/user-service/UserService.i

# target to preprocess a source file
src/services/user-service/UserService.cpp.i:
	$(MAKE) -f CMakeFiles/user-service.dir/build.make CMakeFiles/user-service.dir/src/services/user-service/UserService.cpp.i
.PHONY : src/services/user-service/UserService.cpp.i

src/services/user-service/UserService.s: src/services/user-service/UserService.cpp.s
.PHONY : src/services/user-service/UserService.s

# target to generate assembly for a file
src/services/user-service/UserService.cpp.s:
	$(MAKE) -f CMakeFiles/user-service.dir/build.make CMakeFiles/user-service.dir/src/services/user-service/UserService.cpp.s
.PHONY : src/services/user-service/UserService.cpp.s

src/services/user-service/creatorUserService.o: src/services/user-service/creatorUserService.cpp.o
.PHONY : src/services/user-service/creatorUserService.o

# target to build an object file
src/services/user-service/creatorUserService.cpp.o:
	$(MAKE) -f CMakeFiles/user-service.dir/build.make CMakeFiles/user-service.dir/src/services/user-service/creatorUserService.cpp.o
.PHONY : src/services/user-service/creatorUserService.cpp.o

src/services/user-service/creatorUserService.i: src/services/user-service/creatorUserService.cpp.i
.PHONY : src/services/user-service/creatorUserService.i

# target to preprocess a source file
src/services/user-service/creatorUserService.cpp.i:
	$(MAKE) -f CMakeFiles/user-service.dir/build.make CMakeFiles/user-service.dir/src/services/user-service/creatorUserService.cpp.i
.PHONY : src/services/user-service/creatorUserService.cpp.i

src/services/user-service/creatorUserService.s: src/services/user-service/creatorUserService.cpp.s
.PHONY : src/services/user-service/creatorUserService.s

# target to generate assembly for a file
src/services/user-service/creatorUserService.cpp.s:
	$(MAKE) -f CMakeFiles/user-service.dir/build.make CMakeFiles/user-service.dir/src/services/user-service/creatorUserService.cpp.s
.PHONY : src/services/user-service/creatorUserService.cpp.s

src/utils/md5.o: src/utils/md5.cpp.o
.PHONY : src/utils/md5.o

# target to build an object file
src/utils/md5.cpp.o:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/utils/md5.cpp.o
.PHONY : src/utils/md5.cpp.o

src/utils/md5.i: src/utils/md5.cpp.i
.PHONY : src/utils/md5.i

# target to preprocess a source file
src/utils/md5.cpp.i:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/utils/md5.cpp.i
.PHONY : src/utils/md5.cpp.i

src/utils/md5.s: src/utils/md5.cpp.s
.PHONY : src/utils/md5.s

# target to generate assembly for a file
src/utils/md5.cpp.s:
	$(MAKE) -f CMakeFiles/babel-server-core.dir/build.make CMakeFiles/babel-server-core.dir/src/utils/md5.cpp.s
.PHONY : src/utils/md5.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... babel-server"
	@echo "... babel-server-core"
	@echo "... channel-service"
	@echo "... database-service"
	@echo "... edit_cache"
	@echo "... loggin-service"
	@echo "... rebuild_cache"
	@echo "... user-service"
	@echo "... src/UserController.o"
	@echo "... src/UserController.i"
	@echo "... src/UserController.s"
	@echo "... src/loaders/ClassException.o"
	@echo "... src/loaders/ClassException.i"
	@echo "... src/loaders/ClassException.s"
	@echo "... src/loaders/UnixLibLoader.o"
	@echo "... src/loaders/UnixLibLoader.i"
	@echo "... src/loaders/UnixLibLoader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/managers/BoostManager.o"
	@echo "... src/managers/BoostManager.i"
	@echo "... src/managers/BoostManager.s"
	@echo "... src/network/AServerSocket.o"
	@echo "... src/network/AServerSocket.i"
	@echo "... src/network/AServerSocket.s"
	@echo "... src/network/ASocket.o"
	@echo "... src/network/ASocket.i"
	@echo "... src/network/ASocket.s"
	@echo "... src/network/BoostClientSocket.o"
	@echo "... src/network/BoostClientSocket.i"
	@echo "... src/network/BoostClientSocket.s"
	@echo "... src/network/BoostServer.o"
	@echo "... src/network/BoostServer.i"
	@echo "... src/network/BoostServer.s"
	@echo "... src/network/BoostServerAcceptor.o"
	@echo "... src/network/BoostServerAcceptor.i"
	@echo "... src/network/BoostServerAcceptor.s"
	@echo "... src/packets/APacket.o"
	@echo "... src/packets/APacket.i"
	@echo "... src/packets/APacket.s"
	@echo "... src/packets/PacketAddContact.o"
	@echo "... src/packets/PacketAddContact.i"
	@echo "... src/packets/PacketAddContact.s"
	@echo "... src/packets/PacketAnswer.o"
	@echo "... src/packets/PacketAnswer.i"
	@echo "... src/packets/PacketAnswer.s"
	@echo "... src/packets/PacketAuthentification.o"
	@echo "... src/packets/PacketAuthentification.i"
	@echo "... src/packets/PacketAuthentification.s"
	@echo "... src/packets/PacketCreateChannel.o"
	@echo "... src/packets/PacketCreateChannel.i"
	@echo "... src/packets/PacketCreateChannel.s"
	@echo "... src/packets/PacketFactory.o"
	@echo "... src/packets/PacketFactory.i"
	@echo "... src/packets/PacketFactory.s"
	@echo "... src/packets/PacketGetUserInfos.o"
	@echo "... src/packets/PacketGetUserInfos.i"
	@echo "... src/packets/PacketGetUserInfos.s"
	@echo "... src/packets/PacketHello.o"
	@echo "... src/packets/PacketHello.i"
	@echo "... src/packets/PacketHello.s"
	@echo "... src/packets/PacketLoginSuccess.o"
	@echo "... src/packets/PacketLoginSuccess.i"
	@echo "... src/packets/PacketLoginSuccess.s"
	@echo "... src/packets/PacketRegister.o"
	@echo "... src/packets/PacketRegister.i"
	@echo "... src/packets/PacketRegister.s"
	@echo "... src/packets/PacketUpdateStatus.o"
	@echo "... src/packets/PacketUpdateStatus.i"
	@echo "... src/packets/PacketUpdateStatus.s"
	@echo "... src/packets/PacketUpdateUsername.o"
	@echo "... src/packets/PacketUpdateUsername.i"
	@echo "... src/packets/PacketUpdateUsername.s"
	@echo "... src/packets/PacketUserInfos.o"
	@echo "... src/packets/PacketUserInfos.i"
	@echo "... src/packets/PacketUserInfos.s"
	@echo "... src/services/ServiceManager.o"
	@echo "... src/services/ServiceManager.i"
	@echo "... src/services/ServiceManager.s"
	@echo "... src/services/UserData.o"
	@echo "... src/services/UserData.i"
	@echo "... src/services/UserData.s"
	@echo "... src/services/channel-service/ChannelService.o"
	@echo "... src/services/channel-service/ChannelService.i"
	@echo "... src/services/channel-service/ChannelService.s"
	@echo "... src/services/channel-service/Room.o"
	@echo "... src/services/channel-service/Room.i"
	@echo "... src/services/channel-service/Room.s"
	@echo "... src/services/channel-service/creatorChannelService.o"
	@echo "... src/services/channel-service/creatorChannelService.i"
	@echo "... src/services/channel-service/creatorChannelService.s"
	@echo "... src/services/database-service/DatabaseException.o"
	@echo "... src/services/database-service/DatabaseException.i"
	@echo "... src/services/database-service/DatabaseException.s"
	@echo "... src/services/database-service/FileDatabase.o"
	@echo "... src/services/database-service/FileDatabase.i"
	@echo "... src/services/database-service/FileDatabase.s"
	@echo "... src/services/database-service/FileHelper.o"
	@echo "... src/services/database-service/FileHelper.i"
	@echo "... src/services/database-service/FileHelper.s"
	@echo "... src/services/database-service/creatorDatabaseService.o"
	@echo "... src/services/database-service/creatorDatabaseService.i"
	@echo "... src/services/database-service/creatorDatabaseService.s"
	@echo "... src/services/loggin-service/LogginService.o"
	@echo "... src/services/loggin-service/LogginService.i"
	@echo "... src/services/loggin-service/LogginService.s"
	@echo "... src/services/loggin-service/creatorLogginService.o"
	@echo "... src/services/loggin-service/creatorLogginService.i"
	@echo "... src/services/loggin-service/creatorLogginService.s"
	@echo "... src/services/user-service/UserService.o"
	@echo "... src/services/user-service/UserService.i"
	@echo "... src/services/user-service/UserService.s"
	@echo "... src/services/user-service/creatorUserService.o"
	@echo "... src/services/user-service/creatorUserService.i"
	@echo "... src/services/user-service/creatorUserService.s"
	@echo "... src/utils/md5.o"
	@echo "... src/utils/md5.i"
	@echo "... src/utils/md5.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

